[12512:11232:0314/205140.642:WARNING:chrome_main_delegate.cc(618)] This is Chrome version 111.0.5563.65 (not a warning)
[12512:13884:0314/205140.757:ERROR:model_type_store_service_impl.cc(38)] Failed to initialize ModelTypeStore backend: Init@components\sync\model\model_type_store_backend.cc:109: IO error: S:\PY_BOTVA\SELENIUM\BOTVA\Sync Data\LevelDB/MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::1)
[12512:16752:0314/205140.931:WARNING:leveldb_database.cc(123)] Unable to open S:\PY_BOTVA\SELENIUM\BOTVA\shared_proto_db\metadata: IO error: S:\PY_BOTVA\SELENIUM\BOTVA\shared_proto_db\metadata/MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::1)
[12512:16752:0314/205140.938:WARNING:leveldb_database.cc(123)] Unable to open S:\PY_BOTVA\SELENIUM\BOTVA\shared_proto_db\metadata: IO error: S:\PY_BOTVA\SELENIUM\BOTVA\shared_proto_db\metadata/MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::1)
[12512:16752:0314/205140.944:WARNING:leveldb_database.cc(123)] Unable to open S:\PY_BOTVA\SELENIUM\BOTVA\shared_proto_db\metadata: IO error: S:\PY_BOTVA\SELENIUM\BOTVA\shared_proto_db\metadata/MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::1)
[12512:16752:0314/205140.951:WARNING:leveldb_database.cc(123)] Unable to open S:\PY_BOTVA\SELENIUM\BOTVA\shared_proto_db\metadata: IO error: S:\PY_BOTVA\SELENIUM\BOTVA\shared_proto_db\metadata/MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::1)
[12512:4264:0314/205140.972:WARNING:value_store_frontend.cc(47)] Reading ahfgeienlihckogmohjhadlkjgocpleb.alarms from  failed: IO error: .../MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::1)
[12512:4264:0314/205140.978:WARNING:value_store_frontend.cc(47)] Reading mhjfbmdgcfjbbpaeojofohoefgiehjai.alarms from  failed: IO error: .../MANIFEST-000001: Unable to create sequential file (ChromeMethodBFE: 7::NewSequentialFile::1)
[12512:11232:0314/205142.992:ERROR:device_event_log_impl.cc(222)] [20:51:42.992] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: ѕрисоединенное к системе устройство не работает. (0x1F)
[12512:11232:0314/205142.994:ERROR:device_event_log_impl.cc(222)] [20:51:42.995] USB: usb_device_handle_win.cc:1046 Failed to read descriptor from node connection: ѕрисоединенное к системе устройство не работает. (0x1F)
[12512:11232:0314/205143.121:INFO:CONSOLE(0)] "[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) %o", source: https://avatar.botva.ru/ (0)
[12512:11232:0314/205143.160:INFO:CONSOLE(558)] "Uncaught SyntaxError: Unexpected end of input", source: https://lbn2.ddestiny.ru/static/js/api/destiny_scope.js (558)
[12512:11232:0314/205150.340:INFO:CONSOLE(558)] "Uncaught SyntaxError: Unexpected end of input", source: https://lbn2.ddestiny.ru/static/js/api/destiny_scope.js (558)
[12512:11232:0314/205151.149:INFO:CONSOLE(558)] "Uncaught SyntaxError: Unexpected end of input", source: https://lbn2.ddestiny.ru/static/js/api/destiny_scope.js (558)
[12512:11232:0314/205152.022:WARNING:pref_notifier_impl.cc(41)] Pref observer for media_router.cast_allow_all_ips found at shutdown.
